# Generated by Django 3.2.7 on 2021-10-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_1', '0005_auto_20211008_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
